db:
  dataBase: my_blog
  user: abpvleujrghwbd
  password: efb6b1461b65c2dbcf2a31830cd27757beb730806ba045305fdc09f12af41859
  schema: public

spring.datasource:
  #url: jdbc:postgresql://localhost:5432/${db.dataBase}?currentSchema=${db.schema}
  url: jdbc:postgresql://ec2-52-207-90-231.compute-1.amazonaws.com:5432/d6j4entq7a1a01?sslmode=require
  username: ${db.user}
  password: ${db.password}
  driver-class-name: org.postgresql.Driver

spring:
  mail:
    host: smtp.mail.ru
    port: 587
    username: sansundertalesans@mail.ru
    password: qWtzktmX9A6RbuzxgFkf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: validate
  flyway:
    user: ${db.user}
    password: ${db.password}
    schemas: ${db.schema}
    locations: classpath:db/migration
    baseline-on-migrate: true
    open-in-view: false
server:
    port: 8090

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

