db:
  user: postgres
  password: testtest
  schema: my_blog

spring.datasource:
  url: jdbc:postgresql://localhost:3306/${db.schema}
  username: ${db.user}
  password: ${db.password}
  driver-class-name: org.postgresql.Driver

spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: validate
  flyway:
    user: ${db.user}
    password: ${db.password}
    schemas: ${db.schema}
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
    port: 8090

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

